schema_version: 1

context:
  name: harlequin
  version: "2.12.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/harlequin-${{ version }}.tar.gz
  sha256: 66c0ccf7090903d164a6e00cc88b9fc3844088e328c36556049609553a63fcb6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - harlequin = harlequin.cli:harlequin

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
    - sed
  run:
    - python-duckdb >=1.1.1
    - questionary ==2.1.1
    - tomlkit >=0.15.1,<0.16.0
    - rich-click ==1.9.8
    - python >=${{ python_min }}
    - textual ==8.2.8
    - textual-fastdatatable ==0.19.0
    - textual-textarea ==0.18.1
    - click ==8.4.2
    - shandy-sqlfmt >=0.28.2
    - platformdirs >=3.10,<5.0
    - pyperclip >=1.9,<2
    - tree-sitter-sql >=0.3.11,<0.4
    - wcwidth >=0.2.13,<0.9
    - tree_sitter >=0.25,<0.27
    - tomli >=2.0.1
    - msgspec >=0.19,<1
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - harlequin
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - harlequin --help

about:
  summary: The DuckDB IDE for Your Terminal.
  license: MIT
  license_file: LICENSE
  homepage: https://harlequin.sh
  repository: https://github.com/tconbeer/harlequin

extra:
  recipe-maintainers:
    - moritzwilksch
    - xhochy
