schema_version: 1

context:
  name: harlequin
  version: 2.8.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/harlequin-${{ version }}.tar.gz
  sha256: 6283cdf2394fe063ebcd663a4de6400e83807029d17720be9fbf08831cc0dd97

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - harlequin = harlequin.cli:harlequin

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
    - sed
  run:
    - python-duckdb >=1.1.1
    - questionary ==2.0.1
    - tomlkit >=0.12.5,<0.14.0
    - rich-click ==1.9.8
    - python >=${{ python_min }}
    - textual ==8.2.8
    - textual-fastdatatable ==0.16.0
    - textual-textarea ==0.18.1
    - click ==8.3.3
    - shandy-sqlfmt >=0.28.2
    - platformdirs >=3.10,<5.0
    - pyperclip >=1.9,<2
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - harlequin
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - harlequin --help

about:
  summary: The DuckDB IDE for Your Terminal.
  license: MIT
  license_file: LICENSE
  homepage: https://harlequin.sh
  repository: https://github.com/tconbeer/harlequin

extra:
  recipe-maintainers:
    - moritzwilksch
    - xhochy
